import{a as v,S,i as a}from"./assets/vendor-BkC4bTqC.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const q="55097686-021960f1602add3603143e36a",P="https://pixabay.com/api/";async function f(r,e=1){const o={params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}};return(await v.get(P,o)).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),B=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const e=r.map(o=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b> <span>${o.likes}</span></p>
          <p><b>Views</b> <span>${o.views}</span></p>
          <p><b>Comments</b> <span>${o.comments}</span></p>
          <p><b>Downloads</b> <span>${o.downloads}</span></p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",e),B.refresh()}function M(){m.innerHTML=""}function g(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}function b(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}const u=document.querySelector(".form"),$=document.querySelector(".load-more");let i="",n=1;const w=15;u.addEventListener("submit",async r=>{if(r.preventDefault(),i=r.currentTarget.elements["search-text"].value.trim(),n=1,i===""){a.warning({message:"Please fill the search field"});return}M(),d(),g();try{const e=await f(i,n);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query."});return}y(e.hits),e.totalHits>w&&b()}catch{a.error({message:"Error fetching data!"})}finally{L(),u.reset()}});$.addEventListener("click",async()=>{n+=1,d(),g();try{const r=await f(i,n);y(r.hits),E();const e=Math.ceil(r.totalHits/w);n>=e?(d(),a.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch{a.error({message:"Error loading more images!"})}finally{L()}});function E(){const r=document.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
