import{a as v,S,i as a}from"./assets/vendor-BkC4bTqC.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const q="55097686-021960f1602add3603143e36a",P="https://pixabay.com/api/";async function p(o,e=1){const r={params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}};return(await v.get(P,r)).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more"),R=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const e=o.map(r=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b> <span>${r.likes}</span></p>
          <p><b>Views</b> <span>${r.views}</span></p>
          <p><b>Comments</b> <span>${r.comments}</span></p>
          <p><b>Downloads</b> <span>${r.downloads}</span></p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",e),R.refresh()}function B(){f.innerHTML=""}function y(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function b(){m.classList.remove("hidden")}function c(){m.classList.add("hidden")}const u=document.querySelector(".form"),M=document.querySelector(".load-more");let i="",n=1;const w=15;u.addEventListener("submit",async o=>{if(o.preventDefault(),i=o.currentTarget.elements["search-text"].value.trim(),n=1,i===""){a.warning({message:"Please fill the search field",position:"topRight"});return}B(),c(),y();try{const e=await p(i,n);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(e.hits),e.totalHits>w?b():(c(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({message:"Error fetching data!",position:"topRight"})}finally{L(),u.reset()}});M.addEventListener("click",async()=>{n+=1,c(),y();try{const o=await p(i,n);g(o.hits),$();const e=Math.ceil(o.totalHits/w);n>=e?(c(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch{a.error({message:"Error loading more images!",position:"topRight"})}finally{L()}});function $(){const o=document.querySelector(".gallery-item");if(o){const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
